spring.application.name=lifeNote

#server.port=${SERVER_PORT:8080}

server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/lifenote}
#spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.username=postgres
#spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.password=114713

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

lifenote.security.jwt-secret=${LIFENOTE_JWT_SECRET:bGlmZW5vdGUtc3VwZXItc2VjcmV0LWRldi1rZXktMzItYnl0ZXMhIQ==}
lifenote.security.jwt-expiration-minutes=${LIFENOTE_JWT_EXPIRATION_MINUTES:1440}
lifenote.cors.allowed-origins=${LIFENOTE_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
